[package]
name = "wgpu-sha256-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "24"
bytemuck = "1.21"
sha2 = "0.10"
anyhow = "1.0"
futures = "0.3"

[dev-dependencies]
tokio = { version = "1.44", features = ["full"] }
